// import img from './nnn/hh.png'
export const AllProjects = [
  {
    id: 1,
    name: "Shopping Cart",
    img: "./images/Screenshot (21).png",
    live: "https://shoping-card.vercel.app/",
    repo: "https://github.com/E1442020/shopping-cart",
  },
  {
    id: 2,
    name: "Flowers App",
    img: "./images/Screenshot (22).png",
    live: "https://flower-app-alpha.vercel.app/",
    repo: "https://github.com/E1442020/flower-app",
  },
  {
    id: 3,
    name: "commune-page",
    img: "./images/Screenshot (26).png",
    live: "https://commune-page.vercel.app/",
    repo: "https://commune-page.vercel.app/",
  },
  {
    id: 4,
    name: "Kanban Board",
    img: "./images/kanban.png",
    live: "https://kanban-drag-drop.vercel.app/",
    repo: "https://github.com/E1442020/kanban-drag-drop",
  },
  {
    id: 5,
    name: "Accordion",
    img: "./images/Screenshot (43).png",
    live: "https://according-js.vercel.app/",
    repo: "https://github.com/E1442020/according-js",
  },
  {
    id: 6,
    name: "Quote Generator",
    img: "./images/Screenshot (40).png",
    live: "https://quote-generator-pedz.onrender.com/",
    repo: "https://github.com/E1442020/quote-generator",
  },
  {
    id: 7,
    name: "Contact List",
    img: "./images/Screenshot (27).png",
    live: "https://contact-list-e1442020.vercel.app/",
    repo: "https://github.com/E1442020/contact-list",
  },
  {
    id: 8,
    name: "Notes App",
    img: "./images/Screenshot (23).png",
    live: "https://note-app-e1442020.vercel.app/",
    repo: "https://github.com/E1442020/note-app",
  },
  {
    id: 9,
    name: "Card",
    img: "./images/Screenshot (25).png",
    live: "https://card-6g6i.onrender.com/",
    repo: "https://github.com/E1442020/card-with-sass",
  },
  {
    id: 10,
    name: "Form Authentication",
    img: "./images/Screenshot (28).png",
    live: "https://register-login-form-u07m.onrender.com/",
    repo: "https://github.com/E1442020/login-register-form",
  },
  {
    id: 11,
    name: "Quarter",
    img: "./images/Screenshot (30).png",
    live: "https://quarter.vercel.app/",
    repo: "https://github.com/E1442020/quarter",
  },
  {
    id: 12,
    name: "Converter Length",
    img: "./images/Screenshot (29).png",
    live: "https://converter-length.onrender.com/",
    repo: "https://github.com/E1442020/converter",
  },
  {
    id: 13,
    name: "Quiz App",
    img: "./images/Screenshot (31).png",
    live: "https://ahmed0saber.github.io/quiz-app-t3/",
    repo: "https://github.com/ahmed0saber/quiz-app-t3",
  },
  {
    id: 14,
    name: "Simple Fetch Products",
    img: "./images/Screenshot (32).png",
    live: "https://fetch-api-with-atom.vercel.app/",
    repo: "https://github.com/E1442020/fetch-api-with-atom",
  },
  {
    id: 15,
    name: "Add-Delete Products",
    img: "./images/Screenshot (33).png",
    live: "https://add-delete-getprice-product.vercel.app/",
    repo: "https://github.com/E1442020/add-delete-price-product",
  },
  {
    id: 16,
    name: "Notifications Page",
    img: "./images/Screenshot (34).png",
    live: "https://notification-page.onrender.com/",
    repo: "https://github.com/E1442020/Notifications-page",
  },
  {
    id: 17,
    name: "Movies",
    img: "./images/Screenshot (36).png",
    live: "https://small-movies.vercel.app/",
    repo: "https://github.com/E1442020/small-movies",
  },
  {
    id: 18,
    name: "Book Store",
    img: "./images/Screenshot (37).png",
    live: "https://book-store-xusp.onrender.com/",
    repo: "https://github.com/E1442020/redux-book-store",
  },
  {
    id: 19,
    name: "Quiz App",
    img: "./images/Screenshot (38).png",
    live: "https://quiz-app-with-typescript-react.vercel.app/",
    repo: "https://github.com/E1442020/quiz-app-with-typescript-react",
  },
  {
    id: 20,
    name: "404 Error Page",
    img: "./images/Screenshot (39).png",
    live: "https://four04-error-xom1.onrender.com/",
    repo: "https://github.com/E1442020/404-error",
  },
  {
    id: 21,
    name: "Change Phone",
    img: "./images/Screenshot (42).png",
    live: "https://chang-phone-js.vercel.app/",
    repo: "https://github.com/E1442020/chang-phone-js",
  },
  {
    id: 22,
    name: "Image Editor",
    img: "./images/Screenshot (41).png",
    live: "https://image-editor-js-rust.vercel.app/",
    repo: "https://github.com/E1442020/image-editor-js",
  },
];

export const ReactProjects = [
  {
    id: 19,
    name: "Quiz App",
    img: "./images/Screenshot (38).png",
    live: "https://quiz-app-with-typescript-react.vercel.app/",
    repo: "https://github.com/E1442020/quiz-app-with-typescript-react",
  },
  {
    id: 18,
    name: "Book Store",
    img: "./images/Screenshot (37).png",
    live: "https://book-store-xusp.onrender.com/",
    repo: "https://github.com/E1442020/redux-book-store",
  },
  {
    id: 17,
    name: "Movies",
    img: "./images/Screenshot (36).png",
    live: "https://small-movies.vercel.app/",
    repo: "https://github.com/E1442020/small-movies",
  },
  {
    id: 14,
    name: "Simple Fetch Products",
    img: "./images/Screenshot (32).png",
    live: "https://fetch-api-with-atom.vercel.app/",
    repo: "https://github.com/E1442020/fetch-api-with-atom",
  },
  {
    id: 10,
    name: "Form Authentication",
    img: "./images/Screenshot (28).png",
    live: "https://register-login-form-u07m.onrender.com/",
    repo: "https://github.com/E1442020/login-register-form",
  },
  {
    id: 8,
    name: "Notes App",
    img: "./images/Screenshot (23).png",
    live: "https://note-app-e1442020.vercel.app/",
    repo: "https://github.com/E1442020/note-app",
  },
  {
    id: 6,
    name: "Quote Generator",
    img: "./images/Screenshot (40).png",
    live: "https://quote-generator-pedz.onrender.com/",
    repo: "https://github.com/E1442020/quote-generator",
  },
  {
    id: 4,
    name: "Kanban Board",
    img: "./images/kanban.png",
    live: "https://kanban-drag-drop.vercel.app/",
    repo: "https://github.com/E1442020/kanban-drag-drop",
  },
  {
    id: 1,
    name: "Shopping Cart",
    img: "./images/Screenshot (21).png",
    live: "https://shoping-card.vercel.app/",
    repo: "https://github.com/E1442020/shopping-cart",
  },
  {
    id: 2,
    name: "Flowers App",
    img: "./images/Screenshot (22).png",
    live: "https://flower-app-alpha.vercel.app/",
    repo: "https://github.com/E1442020/flower-app",
  },
];

export const JsProjects = [
  {
    id: 21,
    name: "Change Phone",
    img: "./images/Screenshot (42).png",
    live: "https://chang-phone-js.vercel.app/",
    repo: "https://github.com/E1442020/chang-phone-js",
  },
  {
    id: 22,
    name: "Image Editor",
    img: "./images/Screenshot (41).png",
    live: "https://image-editor-js-rust.vercel.app/",
    repo: "https://github.com/E1442020/image-editor-js",
  },
  {
    id: 15,
    name: "Add-Delete Products",
    img: "./images/Screenshot (33).png",
    live: "https://add-delete-getprice-product.vercel.app/",
    repo: "https://github.com/E1442020/add-delete-price-product",
  },
  {
    id: 12,
    name: "Converter Length",
    img: "./images/Screenshot (29).png",
    live: "https://converter-length.onrender.com/",
    repo: "https://github.com/E1442020/converter",
  },
  {
    id: 13,
    name: "Quiz App",
    img: "./images/Screenshot (31).png",
    live: "https://ahmed0saber.github.io/quiz-app-t3/",
    repo: "https://github.com/ahmed0saber/quiz-app-t3",
  },
  {
    id: 7,
    name: "Contact List",
    img: "./images/Screenshot (27).png",
    live: "https://contact-list-e1442020.vercel.app/",
    repo: "https://github.com/E1442020/contact-list",
  },
  {
    id: 5,
    name: "Accordion",
    img: "./images/Screenshot (43).png",
    live: "https://according-js.vercel.app/",
    repo: "https://github.com/E1442020/according-js",
  },
];

export const HtmlProjects = [
  {
    id: 20,
    name: "404 Error Page",
    img: "./images/Screenshot (39).png",
    live: "https://four04-error-xom1.onrender.com/",
    repo: "https://github.com/E1442020/404-error",
  },
  {
    id: 16,
    name: "Notifications Page",
    img: "./images/Screenshot (34).png",
    live: "https://notification-page.onrender.com/",
    repo: "https://github.com/E1442020/Notifications-page",
  },
  {
    id: 11,
    name: "Quarter",
    img: "./images/Screenshot (30).png",
    live: "https://quarter.vercel.app/",
    repo: "https://github.com/E1442020/quarter",
  },
  {
    id: 9,
    name: "Card",
    img: "./images/Screenshot (25).png",
    live: "https://card-6g6i.onrender.com/",
    repo: "https://github.com/E1442020/card-with-sass",
  },
  {
    id: 3,
    name: "commune-page",
    img: "./images/Screenshot (26).png",
    live: "https://commune-page.vercel.app/",
    repo: "https://commune-page.vercel.app/",
  },
];
